### PR TITLE
Substantial refactors

### PR DESCRIPTION
**Pull request by jamiehowarth0**
Swapped over all endpoints to be async/await Tasks.
Strongly-typed all requests and responses to the Zendesk Sell API.
Unit tests added for initial setup (orders and products seem to require a higher subscription level than available to me).
Constants file added for holding an Owner ID & access token for creating the client.

### CODE REVIEW

**Comment by jamiehowarth0** [comment]
Hey @JonasESmith, would you like to clone this branch & then run the unit tests with your own API keys? It appears products & orders require an Enterprise subscription which I don't have.

**Review by JonasESmith — COMMENTED** [review]
Looks good from what I have read through!

**Comment by jamiehowarth0** [comment]
Excellent! Do feel free to push it out as a v2 Nuget package 😁

**Comment by jamiehowarth0** [comment]
@JonasESmith I'm just about to push it out as a Nuget package. Have you got a Nuget username so I can make you a co-owner of the package?

**Pull request merged**
